language: generic

sudo: true # Otherwise there seems to be no fuse available
dist: trusty

env:
  global:
    - DISPLAY=:99

script:
  - sudo apt-get -qq -y install libjack0 desktop-file-utils xmlstarlet xterm xvfb icewm x11-utils x11-apps netpbm xdotool libgl1-mesa-dri libgl1-mesa-dev mesa-utils libosmesa6 > /dev/null # appstream # TODO: Cache me!
  - gem install dupervisor # To convert ini to yaml files
  - npm install -g asar # to get pacakges.json from resources/app.asar for electron-builder applications
  - # npm install -g @alexlafroscia/yaml-merge # to merge yaml files
  - mkdir $HOME/.icewm/
  - echo "ShowTaskBar = 0" > $HOME/.icewm/preferences
  - echo "TaskBarAutoHide = 1" > $HOME/.icewm/preferences
  - echo "TaskBarShowWorkspaces = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowAllWindows = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowClock = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowMailboxStatus = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowCPUStatus = 0" > $HOME/.icewm/preferences
  - echo "TaskBarShowWindowListMenu = 0" > $HOME/.icewm/preferences
  - # xpra start :99 # Cannot get screenshots to work
  - Xvfb :99 -screen 0 800x600x24 >/dev/null 2>&1 & # Need to set bit depth, otherwise get some black screenshots
  - # until xset -q; do echo "Waiting for X server to start..."; sleep 1; done # We are not immediately using it anyway
  - # Find out which files in data/ have been changed in the last commit
  - #set -x    # Debug #379
  - FILES=$(git log -1 -p data/ | grep +++ | cut -d '/' -f 2- | sed -e 's|dev/null||g')
  - echo "$FILES" ; if [ -z "$FILES" ] ; then echo "Variable FILES is empty." ; fi
  - # Work on these files that have been changed in the last commit
  - # Check if $FILES is not empty
  - if [ -n "$FILES" ] ; then for FILE in $FILES ; do echo "$FILE" ; bash -e code/worker.sh $(readlink -f "$FILE") ; done ; fi

after_script:
  - # xpra stop :99
  - killall Xvfb

branches:
  only:
    - gh-pages     # test the gh-pages branch (it is not tested on Travis CI by default)
    - /(.*)/       # test every other branch
